#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

if (file_exists($__composer_autoload_file = __DIR__.'/vendor/autoload.php')) {
    require $__composer_autoload_file;
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle($input = new Symfony\Component\Console\Input\ArgvInput));
